<article class="subPageContainer clearfix">
    <h2>
        Prosty regulamin dla Twojej wygody!
    </h2>
    <ul class="regulamin clearfix">
        <li>
            Rejestracja w katalogu jest darmowa.
        </li>
        <li>
            Zgłoszenie strony jest równoznaczne z akceptacją waunków regulaminu.
        </li>
        <li>
            Zgłaszający akceptując warunki regulaminu oświadcza iż jest właścicielem bądź reprezentantem właściciela zgłasznego serwisu.
        </li>
        <li>
            Właściciel katalogu nie ponosi odpowiedzialności za treści zgłaszanych stron.
        </li>
        <li>
            Właściciel katalogu zabrania zgłaszania stron o treściach niedozwolonych przez "prawo".
        </li>
        <li>
            Właściciel katalogu zastrzega sobie prawo do usówania stron o treściach zabronionych przez "prawo".
        </li>
        <li>
            Właściciel katalogu zastrzega sobie prawo do usówania stron o niskiej zawartości merytorycznej.
        </li>
        <li>
            Aby usunąć stronę z katalogu należy skontaktować się z właścicielem katalogu za pomocą adresu email podanego przy rejestracji.
        </li>
        <li>
            W przypadku naruszenia zasad regulaminu bądź "prawa" prosimy o niezwłoczny kontakt z administratorem katalogu poprzez dział kontakt.
        </li>
        <li>
            Zabronione jest wielokrotne zgłaszanie tych samych stron, podstron oraz stron o identycznych treściach.
        </li>
        <li>
            Podany link musi prowadzić do strony głównej serwisu.
        </li>
        <li>
            Właściciel katalogu zastrzega sobie prawo do wyłączenia serwisu bez podania przyczyny oraz do zmiany treści regulaminu.
        </li>
    </ul>
</article>