<section id="breadcrumb">
        <a class="C888888" href="/" title="Powrót do strony głównej">orange catalog</a> › [[[kategoria w ktorej jest strona]]] › <?php echo $web->title?>
</section>
<article class="showItem clearfix">
    <section>
            <h3>
                <a href="http://<?php echo $web->www?>" title="<?php echo $web->title?>"> 
                    <?php echo $web->title?>
                </a>
            </h3>
            <em>
                <?php echo $web->data?>
            </em>
            <a href="http://<?php echo $web->www?>" title="<?php echo $web->title?>" class="adress clearfix">
                <?php echo $web->www?>
            </a>
            <p class="description">
                 <?php echo $web->description?></td>
            </p>
            <p>
                <br/><br/><br/><br/><br/><br/>
                <?php echo $web->email?></td> i inne duperele trzeba wyrzucic podkategorie i takie tam gowna
            </p>
    </section>
</article>