<section id="breadcrumb" >
        <a class="C888888" href="/" title="Powrót do strony głównej">orange catalog</a> › <?php echo $web->title?>
</section>

<div style="clear:both">
<table>
    <tr>
        <th>www:</th>
        <td><?php echo $web->www?></td>
    </tr>
    <tr>
        <th>link:</th>
        <td><a href="http://<?php echo $web->www?>" target="_blank">link</a></td>
    </tr>
    <tr>
        <th>tite:</th>
        <td><?php echo $web->title?></td>
    </tr>
    <tr>
        <th>description:</th>
        <td><?php echo $web->description?></td>
    </tr>
    <tr>
        <th>email:</th>
        <td><?php echo $web->email?></td>
    </tr>
    <tr>
        <th>data:</th>
        <td><?php echo $web->data?></td>
    </tr>
</table>
</div>
